### PR TITLE
Guys I have a code in my branch I want to merge those codes to DEVELOP. THANKS. I HAVE SOME MENTAL problem.  benim kafam normal degil anlatabiliyor muyum.. Model bu hani moruk.

### PR DESCRIPTION
**Pull request by dnzgndz**
hayirdir derdin nedir > ? 

Guys I have a code in my branch I want to merge those codes to DEVELOP. THANKS. I HAVE SOME MENTAL problem.  benim kafam normal degil anlatabiliyor muyum.. Model bu hani moruk.

Biz zeytinburnu cocuguyuz...

### CODE REVIEW

**Review by silverhillus — APPROVED** [review]
I didn't get the comments though but congrats with your first pull request!

**Comment by dnzgndz** [comment]
> I didn't get the comments though but congrats with your first pull request!

Fatih hocam. As I said pretty hard to understand. I don't blame you. Thank you for accepting my pull request. I'll try to be more active in here. Try to support me abeeeeee....

**Comment by dnzgndz** [comment]
> > I didn't get the comments though but congrats with your first pull request!
> 
> Fatih hocam. As I said pretty hard to understand. I don't blame you. Thank you for accepting my pull request. I'll try to be more active in here. Try to support me abeeeeee....

Ayikuyun nu ?

**Review by k0x4l — APPROVED** [review]
ok great congrats thanks

**Pull request merged**
